# Generated by Django 2.2.5 on 2019-10-07 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191007_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=15, verbose_name='Device Type')),
                ('location', models.CharField(max_length=5, verbose_name='Location')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_type', models.CharField(choices=[('AG', 'Agent'), ('CU', 'Customer')], default='AG', max_length=5, verbose_name='User Type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
